// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Cart struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

type CartItem struct {
	ID         uuid.UUID
	CartID     uuid.UUID
	ProductID  uuid.UUID
	Quantity   int32
	PriceCents int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
