// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin.sql

package database

import (
	"context"
)

const reset = `-- name: Reset :exec
TRUNCATE TABLE
    refresh_tokens,
    users
RESTART IDENTITY CASCADE
`

func (q *Queries) Reset(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, reset)
	return err
}
