// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  id,
  created_at,
  updated_at,
  name,
  description,
  price_cents,
  stock,
  is_active
) VALUES (
    gen_random_uuid(),
    now(),
    now(),
    $1,
    $2,
    $3,
    $4,
    $5
) RETURNING id, created_at, updated_at, name, description, price_cents, stock, is_active
`

type CreateProductParams struct {
	Name        string
	Description sql.NullString
	PriceCents  int32
	Stock       int32
	IsActive    bool
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Stock,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Stock,
		&i.IsActive,
	)
	return i, err
}

const getProductByID = `-- name: GetProductByID :one
SELECT id, name, price_cents, stock
FROM products
WHERE is_active = true AND id = $1
`

type GetProductByIDRow struct {
	ID         uuid.UUID
	Name       string
	PriceCents int32
	Stock      int32
}

func (q *Queries) GetProductByID(ctx context.Context, id uuid.UUID) (GetProductByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getProductByID, id)
	var i GetProductByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceCents,
		&i.Stock,
	)
	return i, err
}

const getProducts = `-- name: GetProducts :many
SELECT id, name, price_cents, stock
FROM products
WHERE is_active = true
ORDER BY created_at DESC
`

type GetProductsRow struct {
	ID         uuid.UUID
	Name       string
	PriceCents int32
	Stock      int32
}

func (q *Queries) GetProducts(ctx context.Context) ([]GetProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, getProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetProductsRow
	for rows.Next() {
		var i GetProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceCents,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
  name = $2,
  description = $3,
  price_cents = $4,
  stock = $5,
  is_active = $6,
  updated_at = now()
WHERE id = $1
RETURNING id, created_at, updated_at, name, description, price_cents, stock, is_active
`

type UpdateProductParams struct {
	ID          uuid.UUID
	Name        string
	Description sql.NullString
	PriceCents  int32
	Stock       int32
	IsActive    bool
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.Stock,
		arg.IsActive,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.Stock,
		&i.IsActive,
	)
	return i, err
}
